[project]
name = "rt-common"
version = "0.0.0"
dependencies = [
    "ipcs~=0.1.5.post1",
]
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.metadata]
allow-direct-references = true
